apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
    release: 0-5
spec:
  containers:
  - name: frontend
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    app: frontend
    release: "0"
spec:
  containers:
  - name: frontend
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0